name: Preview Link Comment
on:
  deployment_status:

permissions:
  pull-requests: write
  contents: read
  deployments: read

jobs:
  post-comment:
    if: github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Post Preview Link
        uses: mshick/add-pr-comment@v2
        with:
          message: |
            **Render QA Deployment Ready**
            View it here: ${{ github.event.deployment_status.environment_url }}
          allow-repeats: false